import random

# Define the quiz questions and answers
word_definitions = {
"Absolute Assignment" : "This is a policy assignment under which the assignee (person to whom the policy is assigned) receives full control over the policy and also full rights to its benefits. Generally, when a policy is assigned to secure a debt, the owner retains all of the rights in the policy in excess of the debt, despite the fact that the assignment is absolute in form.",
"Accidental Death Benefit (Multiple Indemnity) Rider" : "This rider pays an additional sum to the beneficiary if the insured dies due to a covered accident. The amount paid is a multiple of the policy face amount, such as double or triple the original benefit. Accident death life insurance provides the cheapest way to add a significant amount of coverage for a limited period.",
"Accelerated (Death) Benefits Rider" : "This rider allows the insured to receive a portion of the death benefit before death if the insured has a terminal illness and is expected to die within one-to-two years. Regardless of the amount that’s withdrawn in an accelerated death benefit, it will decrease the death benefit when death occurs.",
"Accumulate Interest Option" : "The “accumulate interest” dividend option allows the policy owner to leave dividends with the insurer to accumulate interest. In turn, the policy owner is required to pay taxes on any interest (profit) that’s generated by the dividend.",
"Assignment Clause" : "This clause allows for the right to transfer policy rights to another person or entity.",
"Automatic Premium Loan Provision (or Rider)" : "This provision allows the insurance company to deduct the overdue premium from an insured’s cash value by the end of the grace period if a payment is missed on a life policy. The insurance company can AUTOMATICALLY take out a LOAN for the insured against her CASH VALUE to cover her PREMIUM if it doesn’t receive payment when due. This automatic premium loan can continue until the policy owner resumes making payments, or the policy runs out of cash value. Once all of a policy owner’s cash value is gone, if she doesn’t start paying, her policy will lapse.",
"Cash Option" : "The “cash” dividend option allows policy owners to cash out the dividends they receive.",
"Cash Surrender Option" : "The “cash surrender” non-forfeiture option allows the policy owner to receive the policy’s cash value. If this option is exercised, at this point, the policy owner no longer has coverage. Typically, the maximum period that a life insurance company may legally defer paying the cash value of a surrendered policy is six months (Delayed Payment provision).",
"Collateral Assignment" : "This is an assignment of a policy to a creditor as security for a debt. The creditor is entitled to be reimbursed out of policy proceeds for the amount that’s owed. Any proceeds above the amount that’s due at the insured’s time of death will be paid to a beneficiary who’s designated by the policy owner.",
"Consideration Clause" : "This clause states a policy owner must pay a premium in exchange for the insurer’s promise to pay benefits. A policy owner’s consideration consists of completing the application and paying the initial premium. The amount and frequency of premium payments are contained in the consideration clause. An example of the clause is, “Please CONSIDER me for insurance. Here is my COMPLETED APPLICATION, INITIAL PREMIUM, including how much and how often I agree to pay. Please consider me.”",
"Dependent Riders (Other Insureds Rider)" : "Dependents may be added as additional (other) insureds through the use of a dependent rider. Other insured riders are typically used for spouses and children.",
"Dividend Options" : "These are the options that a policy owner has when receiving dividend payments from an insurance policy.",
"Entire Contract Provision" : "This provision (or clause) states the insurance policy itself, including any riders, endorsements/amendments, and the application comprises the entire contract between all parties.",
"Exclusions" : "These are features of an insurance policy which states that the policy will not cover certain risks.",
"Extended Term Option" : "This non-forfeiture option permits the policy owner to use the policy’s cash value to buy level, extended term insurance for a specified period. No further premium payments are made.",
"Free-Look Period" : "This period states that the policy owner is permitted a certain number of days once the policy is delivered to examine the policy and return it for a refund of all premiums paid.",
"Grace Period" : "This is a period after the due date of a premium during which the policy remains in force without penalty. If an insured dies during the grace period of a life insurance policy before paying the required annual premium, the beneficiary will receive the face amount of the policy minus any required premiums. For life insurance, the grace period is typically one month.",
"Guaranteed Insurability Rider (Future Increase Option)" : "This rider permits the policy owner to buy additional permanent life insurance coverage, at the insured’s attained age, at predetermined intervals without submitting proof of insurability. It also includes specific events, such as marriage and births, without requiring proof of insurability. Typically, the benefit is allowed every three years, up to the original face amount of the policy.",
"Incontestable Provision (Period)" : "This provision states that the insurance company cannot challenge the validity of the policy once the policy has been in force for a specific period (generally two years). Over the years, case law has established precedence that the incontestable clause applies to cases of fraud.",
"Insuring Clause (or Insuring Agreement)" : "This agreement is the insurer’s basic promise to pay specified benefits to a designated person in the event of a covered loss. The agreement stipulates the scope and limits of coverage, and states, “We ensure to INSURE you for...”",
"Misstatement of Age or Sex Provision" : "This provision allows the insurer to adjust the policy benefits if the insured’s age or sex is misstated on the policy application. The misstatement of age provision allows the insurer to adjust the benefits payable if the age of the insured was misstated when the application for the policy was made. At the time of application, if the insured was older than what’s shown in the policy, benefits would be reduced accordingly. The reverse is true if the insured was younger than listed in the application.",
"Non-Forfeiture Options" : "These are the options an insured has for her cash value if she terminates a policy that has a cash value. For example, “you are closing your account (surrendering your policy); what do you want us to do with your cash (so you don’t forfeit it)?” When a policy owner decides she doesn’t want her insurance policy any longer, she has the option to surrender her policy.",
"One-Year Term Option" : "This dividend option allows the policy owner to exchange the dividend for additional coverage in the form of a one-year term policy.",
"Paid-Up Additions Option" : "This dividend option allows the policy owner to exchange the dividend for an additional single payment whole life policy.",
"Payor Provision (Rider or Clause)" : "This provision waives future premiums for a juvenile life insurance policy if the person who’s responsible for paying the premiums dies or becomes disabled.",
"Policy Loan (Cash Withdrawal) Provisions" : "These provisions apply to policies that have cash value, as well as policy loan and withdrawal provisions. These policies must begin to build cash value after a certain number of years which, in most states, is three years. These loans, with interest, cannot exceed the guaranteed cash value. If the loan exceeds the guaranteed cash value, the policy is no longer in force. The policy owner has the right to the policy’s cash value.",
"Reduced Paid-Up Option" : "This non-forfeiture option allows the policy owner to reduce the policy’s benefit amount and, in turn, cease making premium payments.",
"Reduced Premiums Option" : "This dividend option allows the policy owner to return the dividend payment to the insurer in exchange for a reduction in the following year’s premium payments.",
"Reinstatement Provision" : "This provision allows an insured to put a lapsed policy back in force by producing satisfactory evidence of insurability and paying any required past-due premiums. It permits the policy owner to reinstate a policy that has lapsed as long as the policy owner can provide proof of insurability and pays all back premiums, outstanding loans, and interest.",
"Return of Premium Rider" : "This rider pays the total amount of premiums paid into the policy in addition to the face value, as long as the insured dies within a specific period that’s identified in the policy. It may also return premiums to the policy owner at the end of a specified period, if the insured is still alive.",
"Suicide Clause" : "This clause states that the policy will be voided, and no benefit will be paid, if the insured commits suicide within two years from policy issuance. The primary purpose of a suicide provision is to protect the insurer from applicants who are contemplating suicide.",
"Waiver of Premium Rider" : "This rider allows the policy owner to waive premium payments during a disability and keeps the policy in force. The waiver of premium rider is not a loan and doesn’t provide cash payments to the policy owner. The insurance company is “waiving” the premiums.” In other words, it’s just as if the policy owner made the premiums every month.",
"Execution Clause" : " states that the insurance contract will be executed when both parties (the insurer and the policy owner) have satisfied the conditions of the contract.",
"Modification Provision" : "This provision may be listed separately from the entire contract provisions and states that any changes made to the contract must be in writing and endorsed or attached to the policy. It also states that only an executive officer of the insurer or authorized home office personnel possess the authority to make any changes or modifications or waive a policy provision. A producer or agent is not required to countersign any such modification.",
"Privilege of Change Clause (Policy Change Provision)" : "outlines the conditions under which the company will allow the policy owner to change the policy’s coverage. If the premium is increasing, but the face value remains the same, the insured will not be required to prove insurability. However, the insured is required to prove insurability if the premiums are decreasing or the face value is increasing, since it could result in adverse selection.",
"Applicant Control or Ownership Clause" : "If a proposed insured is under the age of majority (i.e., a minor), a parent or guardian is typically the applicant and the policy owner. When this occurs, the parent may have a provision inserted into the contract that provides him with full control of the policy until the minor reaches a specific age.",
"Revocable Beneficiary Provision" : " means that the policy owner may modify, alter, or change the beneficiary at any time and at her discretion. This is one of the owner rights as provided by the policy. If the owner wants to change the beneficiary, she may simply request a “change of beneficiary form,” complete it, and return it to the insurer.",
"Irrevocable Beneficiary Provision" : "the policy owner or a court of law may designate an irrevocable beneficiary. In this case, the beneficiary designation cannot be changed or modified without the permission or consent of the named beneficiary. If a policy owner names an irrevocable beneficiary, the policy owner must obtain the irrevocable beneficiary’s agreement prior to any assignment. Furthermore, an assignee typically doesn’t have the ability to change an irrevocable beneficiary designation. However, the assignee could change a revocable beneficiary.",
"Mode of Premium (Premium Payment) Provision" : "states that premiums must be paid to an insurer or its representative in order for coverage to be provided and allows the policy owner to select the mode of premium. Insurers vary with regard to the payment modes that are made available. Some policy owners may choose to pay on an annual basis. The policy owner will save the most money (i.e., have lower premiums) if she pays annually, since annual premium payments result in lower administrative and maintenance costs for the insurer. This savings is typically passed to the policy owner. The other methods that are available for the payment of premiums include quarterly, semiannually, or monthly. Since insurers experience substantially higher administrative and maintenance costs when the premium is paid monthly, it’s considered the most costly method.",
"Excess Interest Provision" : "The excess interest provision in life insurance means that the cash value will increase faster than the guaranteed rate if the insurer earns a return that’s greater than the guaranteed rate. Therefore, the excess interest provision allows interest that’s more than the policy’s guaranteed rate of interest to be credited to the cash value account. The following two methods are used for the excess interest provision:\n1. Index-linked Method:  The index-linked method credits the excess interest from earnings tied to an economic indicator (e.g., the Consumer Price Index).\n2. Portfolio Method:  The portfolio method credits the excess interest in direct relation to the insurance company’s earnings on its investments.",
"Non-Forfeiture Cash Values" : "This law requires the policy owner to be given access to any cash value accumulation if she stops paying the policy. In simple terms, this means that a person is allowed to stop paying premiums and not forfeit any of the equity in the policy. The amount of cash value and rate of accumulation will vary by both policy type and company. Additionally, prior to the execution of any non-forfeiture option, the cash value is reduced by any loans that have been taken out.",
"Policy Loan Provision" : " required in all whole life policies, outlines that the policy owner has the right to access this equity at his discretion. This provision, which is supported by the previously reviewed owner’s rights provision, permits the owner to receive an advance against the cash value build-up of the whole life policy.",
"Policy Loan Interest" : "Policy loans reduce the amount of funds that an insurer has to invest and, accordingly, reduce the interest that the insurance company can accumulate. Policy owners are required to pay interest on these loans to offset the interest that the insurance company is missing by not having the funds invested.",
"Individual Use of a Policy Loan" : " The primary advantage of a policy loan is that it provides ready cash for the policy owner without needing to apply or qualify for the loan. Whether it’s to pay debts, pay for emergencies, pay for education expenses, or to be used for a business purpose, a policy owner may use the cash value for any reason when he needs cash. The cash value may also be used as collateral in order to secure another type of loan with a lending institution.",
"Business Use of a Policy Loan" : " Businesses may take out life insurance to safeguard a number of different risks. As the policy’s cash value grows, the company has the option of taking a policy loan for any reason that it deems necessary. Business policy loans encounter the same rules as loans on individual policies with regard to structure, interest, and repayment. The original purpose for the company taking out the policy may be significantly impacted if the policy proceeds are reduced due to an outstanding loan.",
"Taxation" : "policy loans may be taken out of an individual whole life policy without any tax implications as long as the policy remains active. However, this changes if the policy lapses or is surrendered and there’s an outstanding loan that’s greater than the total premiums paid. When a policy with an outstanding loan is lapsed or surrendered (before the insured’s death), any gains (i.e., the amount received via policy loan that exceeds the premiums paid) will be immediately taxed as ordinary income. Additionally, interest that’s paid to the insurer on a policy loan is not tax-deductible. Tax implications for policy loans that are taken on business-owned life insurance are beyond the scope of this course.",
"Right to Defer a Loan" : "insurers typically have the right to defer a policy loan or the payment of the cash value (in most states, this can be for up to six months after its request). This right to defer is designed to protect an insurer if a large number of policy holders decode to make withdrawals at the same time. However, this right to defer doesn’t apply to death benefit claims or automatic premium loan payments.",
"Settlement Options Provision" : "outlines the various ways that the policy’s death benefit may be paid to the beneficiary, as well as who has the authority to decide how the funds will be distributed.",
"Spendthrift Clause" : "stipulates that the policy owner may select a settlement option at the time of application. However, in most cases, the settlement selection is made by the beneficiary following the insured’s death.",
"Withdrawl Provision" : " often used when the policy proceeds are held by the insurer and earn interest. This provision outlines the any steps and requirements for withdrawing any funds left on deposit with the insurer. The beneficiary may have the option to withdraw all of the funds or only a limited amount each year.",
"Long-Term Care Rider" : "If an insured is permanently confined to a nursing home and requires long term care, the policy rider will pay a benefit",
"Waiver of Cost Rider" : "also referred to as the waiver of monthly deductions—is typically reserved for universal life policies. Premiums for a universal life policy can fluctuate. For this reason, insurers generally only offer to waive the monthly cost of the insurance, not the total premium that was being paid by the insured. In this case, the cash value will remain level and continue to collect interest, but it will not grow to the extent that it would have had the full premiums been paid.In some cases, a company may write the rider to waive the guaranteed minimum annual premium instead of the monthly cost of insurance. In this case, the policy’s cash value will grow by the amount of the additional premium payment minus the actual cost of insurance. The cash value will also continue to collect interest.",
"Disability Income Benefit Rider" : "This benefit rider provides an income benefit if the insured is totally and permanently disabled as defined by the policy. This income benefit riders provide for a small, stated benefit, such as 1% of the face amount of the policy, that is payable if the insured is totally disabled. The monthly income paid is generally limited to no more than $1,000 per month. Income benefits begin after the six-month waiting period as previously describe",
"Double Indemnity" : " Policies that pay a multiple of two times the policy face amount are referred to as",
"Triple Indemnity" : "those that pay three times the death benefit for death due to accidents are referred to as",
"Accidental Death and Dismemberment (AD&D) Rider" : "The death benefit that’s paid under accidental death coverage is referred to as the principal sum. The severance (dismemberment) benefit that’s paid under accidental dismemberment is referred to as the capital sum and is most often one-half of the principal sum.A dismemberment involves the loss of a limb as a result of an accident. The loss of use of a limb (i.e., paralysis) may also qualify as a dismemberment loss under some policies. However, the loss of a toe or finger doesn’t qualify. Most policies also pay dismemberment benefits for presumptive types of disability, such as the loss of sight or hearing. The principal sum may be paid when an insured loses any combination of limbs, such as a hand and a foot, an arm and a foot, or both eyes",
"Stork Provision" : "The rider may also allow the policy owner to purchase additional coverage at various milestones (e.g., marriage or the birth of a child). For the birth of a child, it’s often referred to as the ____",
"Cost of Living (Adjustment) Rider" : "This rider automatically increases the face amount of the policy at specified intervals based on increases in the Consumer Price Index (CPI). The CPI measures the inflation rate each year. For example, if there’s a 2% rise in this index, the policy owner’s face amount will increase by 2% for the next year. However, a decrease in the index will not result in the lowering of the policy’s death benefit.",
"EXCHANGE PRIVILEGE RIDER (SUBSTITUTE OR CHANGE OF INSURED RIDER)" : "outlines the conditions and processes for changing the insured of an insurance policy. This rider is typically limited to a business policy that covers a key employee or executive. The goal is to simplify updating the insurance policy when such an insured is no longer employed with the business. Although the exchange privilege rider allows for the policy to continue with the same face amount, the premiums are recalculated based on the new insured’s age, sex, insurability, etc.",
"Level Term Rider" : "adds an additional fixed, level death benefit for a predetermined period at a predetermined cost to the existing face value of a permanent policy.",
"Decreasing Term Rider" : "adds an additional decreasing death benefit to the existing face value of a permanent policy for a predetermined period and at a predetermined cost. The cost of a decreasing term rider is lower than the cost of a level term rider because the benefit amount decreases each year.",
"Increasing Term Rider" : "will allow for an increasing amount of coverage each year. Increasing term riders provide an additional term insurance face amount at death that’s equal to either all premiums paid or the amount of cash value. Increasing term riders may also be referred to as increasing benefit riders and they always increase the cost of the insurance policy.",
"Return of Cash Value Rider" : "is another type of increasing term rider that provides an increasing amount of term insurance that equals the cash value as it accumulates in a whole life policy. This rider allows the cash value to be paid in addition to the face amount. Again, the rider provides an additional term insurance benefit that’s equal to the cash value amount at the time of death.",
"family (Term) Rider" : "When added to an insured’s individual policy, this rider covers the rest of the family, but not the primary insured who’s protected by the individual policy.",
"Spousal (Term) Rider" : "This rider may be added to a primary policy to cover a spouse.",
"Child or children's (Term) Rider" : "This rider may be added to an insured’s policy to cover children or adopted children.",
"Life Insurance Policy Exclusions" : "Insurance policies may contain an exclusion provision which provides the insurer with the right to deny a death claim if death is caused by any of the listed exclusions. Exclusions may be listed in the policy itself or attached as riders and referred to as optional provisions or clauses.",
"Status War Clause" : "is a restrictive type of clause which states that the insured will not possess coverage under an individual life insurance policy while he’s in the military even if he’s killed while away on furlough.",
"Results Clause" : "states that an individual policy doesn’t provide coverage if the insured dies while participating in military activities or during military maneuvers of some sort. If the insured was killed while on furlough, he would be covered under an individual policy",
"Aviation Clause" : "Although it was common years ago, current life insurance policies are unlikely to exclude death for passengers, crew members, or pilots aboard commercial aircraft. However, most life insurance policies will exclude deaths resulting from certain types of high-risk aviation activities.",
"Commission of a Felony (Illegal Activity) Clause" : "Some insurance contracts exclude death or injury when it results from the insured committing a felony or doing something illegal. If included in the policy, the exclusion only applies to persons committing the crime since victims or innocent bystanders are always covered.",
"Illegal Occupation Clause" : "specifies that the insurer is not liable for losses which are attributed to the insured being connected with a felony or participating in any illegal occupation.",
"Intoxicants and Narcotics Clause" : "The insurer will typically deny a claim if the insured is intoxicated or under the influence of narcotics at the time of the loss.",
"Hazardous Occupations, Hobbies, or Avocations Clause" : "Hazardous hobbies or occupations may result in the exclusion of certain causes of death by endorsement, resulting in a refund of premiums paid.",
"Change of Occupation Provision" : "allows the insurer to reduce the maximum benefit payable under the policy if the insured switches to a more hazardous occupation or to reduce the premium rate charged if the insured changes to a less hazardous occupation.", 

# Start of Chapter Exam Questions

"Reduced Paid-up" : "Which of these Nonforfeiture Options continue a build-up of cash value?",
"Evidence of insurability is required when the option is exercised" : "Which of these statements about a Guaranteed Insurability Option rider is NOT TRUE?",
"Full face amount minus any past due premiums" : "An insured is past due on his life insurance premium, but is still within the Grace Period. What will the beneficiary receive if the insured dies during this Grace Period?",
"additional Whole Life coverage at specified times " : "B owns a Whole Life policy with a guaranteed insurability option that allows him to purchase, without evidence of insurability, stated amounts of",
"Living Benefit" : "The Accelerated Death Benefit provision in a life insurance policy is also known as a(n):",
"contest a claim during the Contestable Period" : "The incontestable clause allows an insurer to:",
"Premiums are waived if payor becomes disabled " : "What benefit does the Payor clause on a Juvenile Life policy provide?",
"Exclusion" : "Premiums are waived if payor becomes disabled ",
"$50,000 minus any outstanding policy loans" : "P purchases a $50,000 whole life insurance policy in 2005. One of the questions on the application asks if P engages in scuba diving, to which P answers 'no'. The policy is then issued with no scuba exclusions. In 2010, P takes up scuba diving and dies in a scuba-related accident in 2011. What will the insurer pay to P's beneficiary?",
"Claims are denied under the Suicide clause of the policy" : "How do life insurance companies handle cases where the insured commits suicide within the contract's stated Contestable period?",
"Exclusion" : "N is a student pilot with a large life insurance policy. Which of these features would limit the insurer's obligation in the event N was killed while flying as a student pilot?",
"Must have a terminal illness to qualify" : "Which of the following statements is CORRECT about accelerated death benefits?",
"Reinstatement" : "The provision that can be used to put an insurance policy back in force after it has lapsed due to nonpayment is called:",
"Assign policy ownership to the bank" : "What action can a policyowner take if an application for a bank loan requires collateral?",
"Entire Contract provision" : "What provision in a life insurance policy states that the application is considered part of the contract?",
"Extended Term" : "Which of the following Nonforfeiture options offers the highest death benefit?",
"Reduced Paid-Up option" : "Which of the following is an example of a nonforfeiture option?",
"Modify a Provision in the insurance contract" : "Which of these is NOT considered to be a right given to a policyowner?",
"Waiver of Premium" : "A life insurance policy which ensures that the premium will be paid if the insured becomes disabled has what kind of rider attached?",
"Decreasing Term Rider" : "Additional coverage can be added to a Whole Life policy by adding a(n):",
"Inability of the insured to perform more than 2 Activities of Daily Living (ADL's)" : "A long-term care rider in a life insurance policy pays a daily benefit in the event of which of the following?",
"Accumulation at Interest" : "A policyowner may generate taxable income from which of the following Dividend Options?",
"Entire Contract Provision" : "Which provision prevents an insurer from changing the terms of the contract with the policyowner by referring to documents not found within the policy itself?",
"Only the beneficiary may select" : "All of these statements concerning Settlement Options are true, EXCEPT:",
"is blinded in an accident " : "The Accidental Death and Dismemberment (AD&D) provision in a life insurance policy would pay additional benefits if the insured:",
"policy proceeds" : "M has an insurance policy that also has an outstanding policy loan at the time of M's death. The insurer will deduct the outstanding loan balance from the:",
"Amount of premium payments and when they are due" : "The Consideration clause in a life insurance contract contains what pertinent information?",
"Beneficiary will be paid the Death Benefit" : "P died five years after purchasing a life policy. While investigating the claim, the insurer discovered material misrepresentations made by P during the application process. Which of these actions will the insurer take?",
"Extended Term" : "D owns a Whole Life policy that was purchased 10 years ago. If the premium payments suddenly stop and D takes no additional action, which Nonforfeiture Option will the insurer likely proceed with?",
"$50,000" : "T took out a $50,000 life insurance policy with an Accidental Death and Dismemberment rider. Five years later, T commits suicide. How much will the insurer pay?",
"Paid-up Additional Insurance" : "K owns a Whole Life policy. If K wants an increasing Death Benefit to protect against inflation, which Dividend Option should she chose?",
"$50,000" : "S buys a $50,000 whole life policy with a $50,000 Accidental Death and Dismemberment rider. S dies 1 year later of natural causes. How much will the insurer pay the beneficiary?",
"upon receipt of the policy by the policyowner" : "The free-look provision begins",
"the premiums are based on a younger age" : "The advantage of reinstating an original life policy is",
"Life Income" : "Which of these are NOT an example of a Nonforfeiture option?",
"Coverage will be adjusted to reflect the insured's true age if a misstatement of age is discovered" : "Which statement regarding the Misstatement of Age provision is considered to be true?",
"20-Pay Life accumulates cash value faster than Straight Life" : "A potential client, age 40, would like to purchase a Whole Life policy that will accumulate cash value at a faster rate in the early years of the policy. Which of these statements made by the producer would be correct?",
"When the insured dies or at the policy's maturity date, whichever happens first " : "When is the face amount of a Whole Life policy paid?",
"Past-due interest on a policy loan is added to the total debt " : "Which statement is TRUE in regards to a policy loan?",


}

def quiz():
    score = 0
    num_questions = len(word_definitions)  # Limit to the number of unique definitions

    # Get a list of all words and shuffle them
    words = list(word_definitions.keys())
    random.shuffle(words)

    for i in range(num_questions):
        correct_word = words[i]
        correct_definition = word_definitions[correct_word]

        # Create a list of wrong choices
        wrong_words = random.sample([word for word in words if word != correct_word], 3)
        choices = [correct_word] + wrong_words
        random.shuffle(choices)

        # Display the definition and choices
        print(f"Definition: {correct_definition}")
        print("Choices:")
        for j, word in enumerate(choices, 1):
            print(f"{j}. {word}")

        # Get user's answer
        answer = input("Choose the correct word (1-4): ")

        # Check if the answer is correct
        try:
            if choices[int(answer) - 1] == correct_word:
                print("Correct!")
                score += 1
            else:
                print(f"Incorrect: The right answer was '{correct_word}'.")
        except (ValueError, IndexError):
            print("Invalid input. Please choose a number between 1 and 4.")

        print()  # Print a new line for better readability

    # Print the final score
    print(f"Your final score is: {score}/{num_questions}")

# Run the quiz
quiz()
